apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone-con
  template:
    metadata:
      labels:
        app: reddit-clone-con
    spec:
      containers:
      - name: reddit-clone-con
        image: andynze4/reddit-clone-app:1.0.0-2
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "500m"
        ports:
        - containerPort: 3000
