apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  labels:
    app: reddit-clone-con
spec:
  selector:
    app: reddit-clone-con

  ports:
  - port: 3000
    targetPort: 3000

  type: LoadBalancer
