apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  labels:
    app: reddit-clone-label
spec:
  selector:
    app: reddit-clone-label

  ports:
  - port: 3000
    targetPort: 3000

  type: LoadBalancer
